<?php $user = $this->identity() ?>
<?= $this->doctype() ?>
<?php
$currentLang = $this->layout()->language;
$currentLang ? $currentLang : '';
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle() ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/lightbox.css'))
            ->prependStylesheet($this->basePath('css/jquery-filestyle.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/j-confirm-action.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/readable-bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/lightbox.min.js'))
            ->prependFile($this->basePath('js/jquery-filestyle.min.js'))
            ->prependFile($this->basePath('js/share42/share42.js'))
            ->prependFile($this->basePath('js/app-script.js'))
            ->prependFile($this->basePath('js/j-confirm-action.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>

    <!-- Soc icons -->
    <div class="hidden-xs">
        <div class="share42init" data-top1="300" data-top2="70" data-margin="5"></div>
    </div>
    <!-- end soc icons -->

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/lets-talk.png') ?>" width="40" class="hidden-sm" alt="logo">
                        <span>SocNet</span>
                    </a>
                    <?php if (! $user) : ?>
                    <ul class="nav navbar-nav contact-us-no-identified-user">
                        <li><a href="<?= $this->url('contact-us') ?>"><?= $this->translate('Contact Us') ?></a></li>
                    </ul>
                    <?php endif; ?>
                </div>
                <div class="collapse navbar-collapse">
                    <?php if ($user) : ?>
                        <?= $this->navigation('top_navigation')->menu()->setUlClass("nav navbar-nav")->render() ?>
                        <form class="navbar-form navbar-left" role="search" action="/search" method="post">
                            <div class="form-group">
                                <input class="form-control"
                                       placeholder="<?= $this->translate('Find people') ?>"
                                       type="text" name="searchPeople"
                                >
                            </div>
                            <button type="submit" class="btn btn-default"><?= $this->translate('Search') ?></button>
                        </form>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="<?= $this->url('profile', ['username' => $user->getUsername()]) ?>"
                                   class="dropdown-toggle"
                                   data-toggle="dropdown"
                                   role="button"
                                   aria-expanded="false"
                                   title="<?= $this->getNameOrUsername($this, $user) ?>"
                                >
                                    <span><?= $this->translate('Hi') ?>&nbsp;
                                        <strong><?= $this->cutString($this->getNameOrUsername($this, $user), 8) ?></strong>
                                    </span>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="<?= $this->url('profile', ['username' => $user->getUsername()]) ?>">
                                            <?= $this->translate('Profile') ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?= $this->url('friend') ?>">
                                            <?= $this->translate('Friends') ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?= $this->url('profile', ['username' => $user->getUsername(), 'action' => 'edit']) ?>">
                                            <?= $this->translate('Update profile') ?>
                                        </a>
                                    </li>
                                    <?php if ($user && ($user->getRole() === 'superadmin' || $user->getRole() === 'admin')) : ?>
                                    <li>
                                        <a href="<?= $this->url('admin') ?>">
                                            <?= $this->translate('Admin area') ?>
                                        </a>
                                    </li>
                                    <?php endif; ?>
                                    <li class="divider"></li>
                                    <li>
                                        <form action="<?= $this->url('home', ['action' => 'translate']) ?>" method="get" class="form-inline" id="change-language-form">
                                            <select id="languageElement"
                                                    class="form-control"
                                                    name="language"
                                                    onchange="$('#change-language-form').submit()"
                                            >
                                                <option <?php echo $currentLang === 'en_US' ? 'selected' : '' ?> value="en_US">
                                                    <?= $this->translate('English') ?>
                                                </option>
                                                <option <?php echo $currentLang === 'ru_RU' ? 'selected' : '' ?> value="ru_RU">
                                                    <?= $this->translate('Russian') ?>
                                                </option>
                                            </select>
                                        </form>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <form action="/logout" method="post">
                                            <button class="form-logout"><?= $this->translate('Log Out') ?></button>
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    <?php else : ?>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/register"><?= $this->translate('Sign Up') ?></a></li>
                            <li><a href="/login"><?= $this->translate('Log In') ?></a></li>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
        </div>
        <footer class="footer">
            <hr>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-sm-push-6">
                        <p class="portfolio-box pull-right">
                            <a href="/portfolio"><i class="fa fa-briefcase"></i> <?= $this->translate('Portfolio') ?></a>
                        </p>
                    </div>
                    <div class="col-sm-6 col-sm-pull-6">
                        <p>&copy; <?= $this->getYear() ?> by PHP-User. <?= $this->translate('All rights reserved') ?>.</p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- For scrolling to the top -->
        <a id="back-to-top"
           href="#"
           class="btn btn-primary back-to-top"
           role="button"
           data-toggle="tooltip"
           data-placement="left">
            <span class="glyphicon glyphicon-chevron-up"></span>
        </a>

        <?= $this->inlineScript() ?>

    </body>
</html>
