<?php
$headTitle = 'Admin area';
$this->headTitle($headTitle);
?>
<br>
<?= $this->partial('partial/breadcrumbTemplate', ['headTitle' => $headTitle]) ?>
<br>
<p><?= $this->translate('You have the following capabilities') ?>:</p>
<ul class="list-unstyled">
    <li><a href="/admin/statuses"><?= $this->translate('Manage statuses') ?></a></li>
    <li><a href="/admin/users"><?= $this->translate('Manage users') ?></a></li>
</ul>
